Repository microsoft/devhome, pull requests merged in 2024-01, with the labels that each got.

#2104 Moved the About row to the bottom in Settings Page
  settings/DevHome.Settings/ViewModels/SettingsViewModel.cs
Labels: Needs-Second

#2084 Adding AutomationProperties.Name to Learn More buttons in feedback page
  settings/DevHome.Settings/Strings/en-us/Resources.resw
  settings/DevHome.Settings/Views/FeedbackPage.xaml
Labels: Needs-Second

#2037 Update app install package card height
  tools/SetupFlow/DevHome.SetupFlow/Controls/PackageDetailsTooltip.xaml
  tools/SetupFlow/DevHome.SetupFlow/Views/PackageCatalogView.xaml
  tools/SetupFlow/DevHome.SetupFlow/Views/ShimmerPackageCatalogView.xaml
Labels: Type-Accessibility

#2099 Spec for #2072 - Add some PowerToys utilities
  docs/specs/#2072 - Add some PowerToys utilities/spec.md
  docs/specs/#2072 - Add some PowerToys utilities/v1-environment-variables-settings.png
  docs/specs/#2072 - Add some PowerToys utilities/v1-hosts-file-editor-settings.png
  docs/specs/#2072 - Add some PowerToys utilities/v1-pt-in-dev-home.png
  docs/specs/#2072 - Add some PowerToys utilities/v1-registry-preview-settings.png
  docs/specs/#2072 - Add some PowerToys utilities/v1-settings-page.png
  docs/specs/#2072 - Add some PowerToys utilities/v1-utilities-settings-page.png
  docs/specs/#2072 - Add some PowerToys utilities/v2-pt-in-dev-home.png
  docs/specs/spec-template.md
Labels: Needs-Second

#2095 Update BuildTools and WindowsAppSDK versions in extensionsdk to match Dev Home
  extensionsdk/Microsoft.Windows.DevHome.SDK/Microsoft.Windows.DevHome.SDK.vcxproj
  extensionsdk/Microsoft.Windows.DevHome.SDK/packages.config
Labels: Needs-Second

#2110 Change Widget Pin flow to show preview images
  CoreWidgetProvider/Widgets/SSHWalletWidget.cs
  CoreWidgetProvider/Widgets/Templates/SSHWalletConfigurationTemplate.json
  tools/Dashboard/DevHome.Dashboard/Extensions/ServiceExtensions.cs
  tools/Dashboard/DevHome.Dashboard/Services/IWidgetScreenshotService.cs
  tools/Dashboard/DevHome.Dashboard/Services/WidgetScreenshotService.cs
  tools/Dashboard/DevHome.Dashboard/ViewModels/AddWidgetViewModel.cs
  tools/Dashboard/DevHome.Dashboard/ViewModels/WidgetViewModel.cs
  tools/Dashboard/DevHome.Dashboard/Views/AddWidgetDialog.xaml
  tools/Dashboard/DevHome.Dashboard/Views/AddWidgetDialog.xaml.cs
  tools/Dashboard/DevHome.Dashboard/Views/DashboardView.xaml.cs
Labels: Needs-Second

#2062 Adding "open new window" icon to "Create Dev Drive" button (#1334)
  src/Models/WhatsNewCard.cs
  src/Views/WhatsNewPage.xaml
  src/Views/WhatsNewPage.xaml.cs
Labels: Needs-Second

#2129 Add error display to core widgets.
  CoreWidgetProvider/Widgets/SSHWalletWidget.cs
  CoreWidgetProvider/Widgets/SystemCPUUsageWidget.cs
  CoreWidgetProvider/Widgets/SystemGPUUsageWidget.cs
  CoreWidgetProvider/Widgets/SystemMemoryWidget.cs
  CoreWidgetProvider/Widgets/SystemNetworkUsageWidget.cs
  CoreWidgetProvider/Widgets/Templates/SSHWalletTemplate.json
  CoreWidgetProvider/Widgets/Templates/SystemCPUUsageTemplate.json
  CoreWidgetProvider/Widgets/Templates/SystemGPUUsageTemplate.json
  CoreWidgetProvider/Widgets/Templates/SystemMemoryTemplate.json
  CoreWidgetProvider/Widgets/Templates/SystemNetworkUsageTemplate.json
Labels: Area-Widgets, Needs-Second

#2154 Update Dev Home Intro page
  src/Strings/en-us/Resources.resw
  src/Views/WhatsNewPage.xaml
Labels: Needs-Second

#2164 Support mouse and forward navigation
  common/Services/INavigationService.cs
  src/Services/NavigationService.cs
  src/Views/ShellPage.xaml.cs
Labels: Needs-Second

#2182 Remove unused code in Dashboard
  tools/Dashboard/DevHome.Dashboard/Services/WidgetHostingService.cs
  tools/Dashboard/DevHome.Dashboard/ViewModels/AddWidgetViewModel.cs
  tools/Dashboard/DevHome.Dashboard/ViewModels/WidgetViewModel.cs
Labels: Needs-Second

#2167 Add sync repo step to winget-submit workflow
  .github/workflows/winget-submission.yml
Labels: Needs-Second

#2183 Add error messages for DSC configuration in summary page
  tools/SetupFlow/DevHome.SetupFlow.Common/Configuration/ConfigurationFileHelper.cs
  tools/SetupFlow/DevHome.SetupFlow.Common/Exceptions/OpenConfigurationSetException.cs
  tools/SetupFlow/DevHome.SetupFlow.Common/Exceptions/WinGetConfigurationException.cs
  tools/SetupFlow/DevHome.SetupFlow.ElevatedComponent/Helpers/ElevatedConfigureUnitTaskResult.cs
  tools/SetupFlow/DevHome.SetupFlow.ElevatedComponent/Tasks/ElevatedConfigurationTask.cs
  tools/SetupFlow/DevHome.SetupFlow/Models/ConfigurationUnitResult.cs
  tools/SetupFlow/DevHome.SetupFlow/Services/StringResourceKey.cs
  tools/SetupFlow/DevHome.SetupFlow/Strings/en-us/Resources.resw
  tools/SetupFlow/DevHome.SetupFlow/ViewModels/ConfigurationFileViewModel.cs
  tools/SetupFlow/DevHome.SetupFlow/ViewModels/ConfigurationUnitResultViewModel.cs
Labels: Needs-Second

#2189 New WinGet Configuration File for C# software development
  sampleConfigurations/Templates/Introduction/C#/README.md
  sampleConfigurations/Templates/Introduction/C#/configuration.dsc.yaml
Labels: Needs-Second

#2192 New WinGet Configuration File PowerShell software development
  sampleConfigurations/Templates/Introduction/PowerShell/README.md
  sampleConfigurations/Templates/Introduction/PowerShell/configuration.dsc.yaml
Labels: Needs-Second

#2193 New Folders for Sample Configuraiton
  sampleConfigurations/Templates/Android Apps/README.md
  sampleConfigurations/Templates/Web Development/README.md
  sampleConfigurations/Templates/Xbox Games/README.md
Labels: Needs-Second

#2190 New WinGet Configuration File for C++ software development
  sampleConfigurations/Templates/Introduction/C++/README.md
  sampleConfigurations/Templates/Introduction/C++/configuration.dsc.yaml
Labels: Needs-Second

#2197 Append DSC error description messages when applicable
  tools/SetupFlow/DevHome.SetupFlow.ElevatedComponent/Helpers/ElevatedConfigureUnitTaskResult.cs
  tools/SetupFlow/DevHome.SetupFlow.ElevatedComponent/Tasks/ElevatedConfigurationTask.cs
  tools/SetupFlow/DevHome.SetupFlow/Models/ConfigurationUnitResult.cs
  tools/SetupFlow/DevHome.SetupFlow/ViewModels/ConfigurationUnitResultViewModel.cs
  tools/SetupFlow/DevHome.SetupFlow/Views/SummaryView.xaml
Labels: Needs-Second
