Repository microsoft/devhome, pull requests merged in 2024-09, with the labels that each got.

#3724 Use localized strings for file and folder status
  extensions/GitExtension/FileExplorerGitIntegration.UnitTest/GitLocalRepositoryProviderUnitTests.cs
  extensions/GitExtension/FileExplorerGitIntegration/Models/RepositoryWrapper.cs
  extensions/GitExtension/FileExplorerGitIntegration/Strings/en-us/Resources.resw
Labels: Needs-Second, Type-Localization, Area-FileExplorerIntegration

#3707 [File Explorer Source Control Integration] Improve Error Flows
  extensions/GitExtension/FileExplorerGitIntegration/Models/GitLocalRepository.cs
  extensions/GitExtension/FileExplorerGitIntegration/Models/GitLocalRepositoryProviderFactory.cs
  extensions/GitExtension/FileExplorerGitIntegration/Strings/en-us/Resources.resw
  tools/Customization/DevHome.Customization/Helpers/ErrorType.cs
  tools/Customization/DevHome.Customization/Helpers/SourceControlValidationResult.cs
  tools/Customization/DevHome.Customization/Models/SourceControlIntegration.cs
  tools/Customization/DevHome.Customization/Strings/en-us/Resources.resw
  tools/Customization/DevHome.Customization/ViewModels/FileExplorerViewModel.cs
  tools/Customization/DevHome.Customization/Views/AddRepositoriesView.xaml.cs
Labels: Needs-Second, Area-FileExplorerIntegration

#3771 Only show end task setting on Windows 11
  tools/Customization/DevHome.Customization/ViewModels/GeneralSystemViewModel.cs
  tools/Customization/DevHome.Customization/Views/GeneralSystemView.xaml
Labels: Area-Customization

#3761 prevent the more options button in environments cards from being cut off when text is scaled to 200%
  common/Environments/Styles/HorizontalCardStyles.xaml
Labels: Needs-Second

#3752 fix environment deletion dialog to respect theme changes
  tools/Environments/DevHome.Environments/Strings/en-us/Resources.resw
  tools/Environments/DevHome.Environments/ViewModels/OperationsViewModel.cs
Labels: Needs-Second

#3784 Reset AdaptiveCardFlowNavigator when machine configuration ends a flow
  tools/SetupFlow/DevHome.SetupFlow/Models/AdaptiveCardFlowNavigator.cs
  tools/SetupFlow/DevHome.SetupFlow/ViewModels/SetupFlowViewModel.cs
Labels: Needs-Second

#3681 Expect WidgetsPlatformRuntime on Windows 11
  src/ViewModels/InitializationViewModel.cs
  tools/Dashboard/DevHome.Dashboard/Helpers/WidgetHelpers.cs
  tools/Dashboard/DevHome.Dashboard/Services/IWidgetServiceService.cs
  tools/Dashboard/DevHome.Dashboard/Services/WidgetServiceService.cs
  tools/Dashboard/DevHome.Dashboard/Strings/en-us/Resources.resw
  tools/Dashboard/DevHome.Dashboard/Views/DashboardView.xaml
  tools/Dashboard/DevHome.Dashboard/Views/DashboardView.xaml.cs
Labels: Needs-Second

#3783 [FE + Version Control] Accessibility Insights Fast Pass: Section 508 502.3.1: (DevHome/button '') The Name property must not contain any characters in the private Unicode range.
  tools/Customization/DevHome.Customization/Strings/en-us/Resources.resw
  tools/Customization/DevHome.Customization/Views/AddRepositoriesView.xaml
Labels: Area-FileExplorerIntegration

#3808 Fix environment card text colors for high contrast users
  common/Environments/Styles/HorizontalCardStyles.xaml
  tools/SetupFlow/DevHome.SetupFlow/Views/SetupTargetView.xaml
Labels: Needs-Second

#3825 [FE+version control] Surface feature in Stable and update DevHome.Helpers to 1.0.20240910-x0103
  common/DevHome.Common.csproj
  src/DevHome.csproj
  src/NavConfig.jsonc
  tools/QuietBackgroundProcesses/DevHome.QuietBackgroundProcesses.ElevatedServer/DevHome.QuietBackgroundProcesses.ElevatedServer.vcxproj
  tools/QuietBackgroundProcesses/DevHome.QuietBackgroundProcesses.ElevatedServer/packages.config
  tools/QuietBackgroundProcesses/DevHome.QuietBackgroundProcesses.Server/DevHome.QuietBackgroundProcesses.Server.vcxproj
  tools/QuietBackgroundProcesses/DevHome.QuietBackgroundProcesses.Server/packages.config
Labels: Area-FileExplorerIntegration

#3832 [File Explorer Git Integration] Trim version control properties to 80 chars.
  tools/Customization/DevHome.FileExplorerSourceControlIntegration/SourceControlProvider.cs
Labels: Area-FileExplorerIntegration

#3844 Disable Quickstart Playground after the experimental feature is turned off
  tools/SetupFlow/DevHome.SetupFlow/ViewModels/MainPageViewModel.cs
  tools/SetupFlow/DevHome.SetupFlow/ViewModels/QuickstartPlaygroundViewModel.cs
  tools/SetupFlow/DevHome.SetupFlow/ViewModels/SetupFlowViewModel.cs
  tools/SetupFlow/DevHome.SetupFlow/Views/QuickstartPlaygroundView.xaml
Labels: Needs-Second

#3862 Unsubscribe from OnExtensionsChanged when unloading Extensions page
  DevHome.sln
  tools/ExtensionLibrary/DevHome.ExtensionLibrary/ViewModels/ExtensionLibraryViewModel.cs
  tools/ExtensionLibrary/DevHome.ExtensionLibrary/Views/ExtensionLibraryView.xaml
Labels: Needs-Second

#3868 Prevent Dev Home crashing when widgets don't supply icons or screenshots
  tools/Dashboard/DevHome.Dashboard/Services/IWidgetIconService.cs
  tools/Dashboard/DevHome.Dashboard/Services/IWidgetScreenshotService.cs
  tools/Dashboard/DevHome.Dashboard/Services/WidgetIconService.cs
  tools/Dashboard/DevHome.Dashboard/Services/WidgetScreenshotService.cs
  tools/Dashboard/DevHome.Dashboard/ViewModels/AddWidgetViewModel.cs
  tools/Dashboard/DevHome.Dashboard/Views/AddWidgetDialog.xaml.cs
Labels: Needs-Second

#3839 GitExecute changes for WSL
  extensions/GitExtension/FileExplorerGitIntegration.UnitTest/WslIntegratorUnitTests.cs
  extensions/GitExtension/FileExplorerGitIntegration/Models/GitExecute.cs
  extensions/GitExtension/FileExplorerGitIntegration/Models/WslIntegrator.cs
Labels: Area-FileExplorerIntegration

#3893 Git command line changes for WSL
  extensions/GitExtension/FileExplorerGitIntegration/Helpers/GitCommandRunnerResultInfo.cs
  extensions/GitExtension/FileExplorerGitIntegration/Models/CommitLogCache.cs
  extensions/GitExtension/FileExplorerGitIntegration/Models/CommitWrapper.cs
  extensions/GitExtension/FileExplorerGitIntegration/Models/GitExeceutableConfigOptions.cs
  extensions/GitExtension/FileExplorerGitIntegration/Models/GitExecute.cs
  extensions/GitExtension/FileExplorerGitIntegration/Models/GitLocalRepository.cs
  extensions/GitExtension/FileExplorerGitIntegration/Models/GitLocalRepositoryProviderFactory.cs
  extensions/GitExtension/FileExplorerGitIntegration/Models/GitRepositoryStatus.cs
  extensions/GitExtension/FileExplorerGitIntegration/Models/RepositoryCache.cs
  extensions/GitExtension/FileExplorerGitIntegration/Models/RepositoryWrapper.cs
  extensions/GitExtension/FileExplorerGitIntegration/Models/StatusCache.cs
  extensions/GitExtension/FileExplorerGitIntegration/Models/ThrottledTask.cs
Labels: Needs-Second, Area-FileExplorerIntegration
