Repository microsoft/devhome, pull requests merged in 2024-04, with the labels that each got.

#2439 [Dev Environments docs] Add initial docs for the Dev Environment feature
  docs/environments/Environments-General.md
  docs/environments/Interfaces/IComputeSystem.md
  docs/environments/Interfaces/IComputeSystemProvider.md
Labels: Needs-PM

#2515 Make CPU and Memory widgets single instance, better handle these widgets
  src/Package.appxmanifest
  tools/Dashboard/DevHome.Dashboard/Views/DashboardView.xaml.cs
Labels: Needs-Second

#2495 Add summary view in configuration file page
  tools/SetupFlow/DevHome.SetupFlow.Common/Configuration/ConfigurationFileHelper.cs
  tools/SetupFlow/DevHome.SetupFlow/Models/Configuration.cs
  tools/SetupFlow/DevHome.SetupFlow/Models/DSCConfigurationUnit.cs
  tools/SetupFlow/DevHome.SetupFlow/Services/DesiredStateConfiguration.cs
  tools/SetupFlow/DevHome.SetupFlow/Services/IDesiredStateConfiguration.cs
  tools/SetupFlow/DevHome.SetupFlow/Strings/en-us/Resources.resw
  tools/SetupFlow/DevHome.SetupFlow/ViewModels/ConfigurationFileViewModel.cs
  tools/SetupFlow/DevHome.SetupFlow/ViewModels/DSCConfigurationUnitViewModel.cs
  tools/SetupFlow/DevHome.SetupFlow/Views/ConfigurationFileView.xaml
  tools/SetupFlow/DevHome.SetupFlow/Views/ConfigurationFileView.xaml.cs
Labels: Needs-Second

#2490 Announcing the heading group, and repo names.
  tools/SetupFlow/DevHome.SetupFlow/Services/StringResourceKey.cs
  tools/SetupFlow/DevHome.SetupFlow/Strings/en-us/Resources.resw
  tools/SetupFlow/DevHome.SetupFlow/ViewModels/AddRepoViewModel.cs
  tools/SetupFlow/DevHome.SetupFlow/ViewModels/MainPageViewModel.cs
  tools/SetupFlow/DevHome.SetupFlow/Views/AddRepoDialog.xaml
  tools/SetupFlow/DevHome.SetupFlow/Views/AddRepoDialog.xaml.cs
  tools/SetupFlow/DevHome.SetupFlow/Views/MainPageView.xaml
Labels: Needs-Second

#2492 Refactor Win32 file dialog API
  common/Extensions/WindowExExtensions.cs
  common/NativeMethods.txt
  common/Windows/FileDialog/IWindowFileDialogFilter.cs
  common/Windows/FileDialog/WindowFileDialog.cs
  common/Windows/FileDialog/WindowFileDialogFilter.cs
  common/Windows/FileDialog/WindowOpenFileDialog.cs
  common/Windows/FileDialog/WindowOpenFolderDialog.cs
  common/Windows/FileDialog/WindowSaveFileDialog.cs
  docs/common/Readme.md
  docs/common/WindowOpenFileDialog.md
  docs/common/WindowOpenFolderDialog.md
  docs/common/WindowSaveFileDialog.md
  tools/SetupFlow/DevHome.SetupFlow/ViewModels/ConfigurationFileViewModel.cs
  tools/SetupFlow/DevHome.SetupFlow/ViewModels/DevDriveViewModel.cs
  tools/SetupFlow/DevHome.SetupFlow/ViewModels/FolderPickerViewModel.cs
Labels: Needs-Second

#2516 Fix accessibility bugs: high contrast background + narrator description
  tools/SetupFlow/DevHome.SetupFlow/Styles/AppManagement_ThemeResources.xaml
  tools/SetupFlow/DevHome.SetupFlow/Views/PackageCatalogListView.xaml
Labels: Needs-Second

#2466 Initial support for generating a configuration file from machine configuration
  tools/SetupFlow/DevHome.SetupFlow/Models/ISetupTaskGroup.cs
  tools/SetupFlow/DevHome.SetupFlow/Models/WingetConfigure/WinGetDscSettings.cs
  tools/SetupFlow/DevHome.SetupFlow/Services/ConfigurationFileBuilder.cs
  tools/SetupFlow/DevHome.SetupFlow/Services/PackageProvider.cs
  tools/SetupFlow/DevHome.SetupFlow/Services/StringResourceKey.cs
  tools/SetupFlow/DevHome.SetupFlow/Strings/en-us/Resources.resw
  tools/SetupFlow/DevHome.SetupFlow/Styles/AppManagement_ThemeResources.xaml
  tools/SetupFlow/DevHome.SetupFlow/TaskGroups/AppManagementTaskGroup.cs
  tools/SetupFlow/DevHome.SetupFlow/TaskGroups/ConfigurationFileTaskGroup.cs
  tools/SetupFlow/DevHome.SetupFlow/TaskGroups/DevDriveTaskGroup.cs
  tools/SetupFlow/DevHome.SetupFlow/TaskGroups/RepoConfigTaskGroup.cs
  tools/SetupFlow/DevHome.SetupFlow/TaskGroups/SetupTargetTaskGroup.cs
  tools/SetupFlow/DevHome.SetupFlow/ViewModels/AppManagementViewModel.cs
  tools/SetupFlow/DevHome.SetupFlow/ViewModels/PackageViewModel.cs
  tools/SetupFlow/DevHome.SetupFlow/ViewModels/ReviewViewModel.cs
  tools/SetupFlow/DevHome.SetupFlow/ViewModels/SummaryViewModel.cs
  tools/SetupFlow/DevHome.SetupFlow/Views/AppManagementView.xaml
  tools/SetupFlow/DevHome.SetupFlow/Views/PackageView.xaml
  tools/SetupFlow/DevHome.SetupFlow/Views/ReviewView.xaml
Labels: Needs-Second

#2543 Fix classIds pointing to wrong extensions in package.manifest
  src/Package.appxmanifest
Labels: Needs-Second

#2545 Adding AutomationProperties.Name string to dashboard page
  tools/Dashboard/DevHome.Dashboard/Strings/en-us/Resources.resw
  tools/Dashboard/DevHome.Dashboard/Views/DashboardView.xaml
Labels: Needs-Second

#2571 Using Content in SecondaryWindow
  common/Windows/SecondaryWindow.cs
Labels: Needs-Second

#2576 Reorganize developer documentation
  CONTRIBUTING.md
  README.md
  docs/architecture.md
  docs/extensions/environments/Interfaces/IComputeSystem.md
  docs/extensions/environments/Interfaces/IComputeSystemProvider.md
  docs/extensions/environments/readme.md
  docs/extensions/readme.md
  docs/readme.md
  docs/roadmap.md
  docs/sampleConfigurations/Templates/Introduction/C#/README.md
  docs/sampleConfigurations/Templates/Introduction/C#/configuration.dsc.yaml
  docs/sampleConfigurations/Templates/Introduction/C++/README.md
  docs/sampleConfigurations/Templates/Introduction/C++/configuration.dsc.yaml
  docs/sampleConfigurations/Templates/Introduction/JavaScript.NodeJS/README.md
  docs/sampleConfigurations/Templates/Introduction/JavaScript.NodeJS/configuration.dsc.yaml
  docs/sampleConfigurations/Templates/Introduction/PowerShell/README.md
  docs/sampleConfigurations/Templates/Introduction/Python3.12/README.md
  docs/sampleConfigurations/Templates/Introduction/Python3.12/configuration.dsc.yaml
  docs/sampleConfigurations/Templates/Introduction/README.md
  docs/tools.md
  docs/tools/ExperimentalFeatures.md
  docs/tools/advanced-tool-behavior.md
  docs/tools/common/CloseButton.md
  docs/tools/common/Readme.md
  docs/tools/common/SecondaryWindow.md
  docs/tools/common/StringResource.md
  docs/tools/common/WindowOpenFileDialog.md
  docs/tools/common/WindowOpenFolderDialog.md
  docs/tools/common/WindowSaveFileDialog.md
  docs/tools/common/WindowTitleBar.md
  docs/tools/creating-a-tool.md
  docs/tools/navconfig.md
  docs/tools/readme.md
  src/README.md
Labels: Needs-Second

#2609 [Customization] Make dev drive query async to avoid UI delay
  tools/Customization/DevHome.Customization/ViewModels/MainPageViewModel.cs
  tools/Customization/DevHome.Customization/Views/MainPageView.cs
  tools/Customization/DevHome.Customization/Views/MainPageView.xaml
Labels: Type-Performance, Area-DevDriveInsights, Area-Customization

#2582 Customization craftsmanship review updates
  tools/Customization/DevHome.Customization/Customization.md
  tools/Customization/DevHome.Customization/DevHome.Customization.csproj
  tools/Customization/DevHome.Customization/Extensions/PageExtensions.cs
  tools/Customization/DevHome.Customization/Extensions/ServiceExtensions.cs
  tools/Customization/DevHome.Customization/Models/FileExplorerSettings.cs
  tools/Customization/DevHome.Customization/Strings/en-us/Resources.resw
  tools/Customization/DevHome.Customization/ViewModels/FileExplorerViewModel.cs
  tools/Customization/DevHome.Customization/ViewModels/MainPageViewModel.cs
  tools/Customization/DevHome.Customization/Views/FileExplorerPage.xaml
  tools/Customization/DevHome.Customization/Views/FileExplorerPage.xaml.cs
  tools/Customization/DevHome.Customization/Views/FileExplorerView.xaml
  tools/Customization/DevHome.Customization/Views/FileExplorerView.xaml.cs
  tools/Customization/DevHome.Customization/Views/MainPage.xaml.cs
  tools/Customization/DevHome.Customization/Views/MainPageView.xaml
  tools/Customization/DevHome.Customization/Views/MainPageView.xaml.cs
  tools/Customization/DevHome.Customization/Views/QuietBackgroundProcessesView.xaml
Labels: Type-Craftsmanship, Area-Customization

#2621 [Customization] Make quiet mode initialization async to avoid UI delay
  tools/Customization/DevHome.Customization/ViewModels/QuietBackgroundProcessesViewModel.cs
  tools/Customization/DevHome.Customization/Views/QuietBackgroundProcessesView.xaml
  tools/Customization/DevHome.Customization/Views/QuietBackgroundProcessesView.xaml.cs
Labels: Type-Performance, Area-Customization

#2652 Move PowerToys.dsc.yaml to correct directory
  docs/sampleConfigurations/DscResources/PowerToysConfigure/PowerToys.dsc.yaml
Labels: Needs-Second

#2687 Change GetWidgetsAsync to always return a valid list
  tools/Dashboard/DevHome.Dashboard/Services/IWidgetHostingService.cs
  tools/Dashboard/DevHome.Dashboard/Services/WidgetHostingService.cs
  tools/Dashboard/DevHome.Dashboard/Views/DashboardView.xaml.cs
Labels: Needs-Second

#2689 Only show quiet mode view when the feature is present
  tools/QuietBackgroundProcesses/DevHome.QuietBackgroundProcesses.UI/Views/QuietBackgroundProcessesView.xaml
Labels: Area-QuietMode

#2718 Add third party notices link to Settings About
  NOTICE.txt
  settings/DevHome.Settings/Strings/en-us/Resources.resw
  settings/DevHome.Settings/ViewModels/AboutViewModel.cs
  settings/DevHome.Settings/Views/AboutPage.xaml
  src/DevHome.csproj
Labels: Needs-Second

#2723 Scale widget size with system Text Size
  tools/Dashboard/DevHome.Dashboard/Controls/WidgetBoard.cs
  tools/Dashboard/DevHome.Dashboard/Controls/WidgetControl.xaml
  tools/Dashboard/DevHome.Dashboard/Controls/WidgetControl.xaml.cs
  tools/Dashboard/DevHome.Dashboard/Helpers/WidgetHelpers.cs
Labels: Needs-Second

#2305 Spec for #2160 - Generate a configuration file
  docs/specs/#2160 - Generate a Configuration File/GenerateConfigurationFileSpec.md
Labels: Needs-Design, Needs-Team-Response, Spec-In Review

#2306 Spec for #2211 - Detect a configuration file
  docs/specs/#2211 - Detect Configuration Files/DetectConfigurationFilesSpec.md
Labels: Needs-Design, Needs-Team-Response, Spec-In Review
